<template>
    <div class="pgp">
        <h3>Pretty Good Privacy</h3>
        <h4>Design</h4>
        <p>
            PGP encryption uses a serial combination of hashing, data compression, symmetric-key cryptography, and finally public-key cryptography; each step uses one of several supported algorithms. Each public key is bound to a username or an e-mail address. The first version of this system was generally known as a web of trust to contrast with the X.509 system, which uses a hierarchical approach based on certificate authority and which was added to PGP implementations later. Current versions of PGP encryption include both options through an automated key management server.
        </p>
        <p><b>PGP fingerprint</b></p>
        <p>
            A public key fingerprint is a shorter version of a public key. From a fingerprint, someone can validate the correct corresponding public key. A fingerprint like C3A6 5E46 7B54 77DF 3C4C 9790 4D22 B3CA 5B32 FF66 can be printed on a business card
        </p>
        <p><b>Confidentiality</b></p>
        <p>
            PGP can be used to send messages confidentially. For this, PGP uses hybrid cryptosystem by combining symmetric-key encryption and public-key encryption. The message is encrypted using a symmetric encryption algorithm, which requires a symmetric key generated by the sender. The symmetric key is used only once and is also called a session key. The message and its session key are sent to the receiver. The session key must be sent to the receiver so they know how to decrypt the message, but to protect it during transmission it is encrypted with the receiver's public key. Only the private key belonging to the receiver can decrypt the session key, and use it to symmetrically decrypt the message.
        </p>
        <p>
            <u>Read more at:</u> https://en.wikipedia.org/wiki/Pretty_Good_Privacy
        </p>
    </div>
</template>

<script>
export default {
  name: 'WhatPGP',
  data: function() {
      return {
        errors: []
      }
  },
  methods: {
  }
}
</script>

<style scoped>
.pgp h3, h4 {
    text-align: left;
}

h4 {
    text-align: left;
    border-bottom: 1px black solid;
}

p {
    text-align: left;
    color: black;
}
</style>